name: Deploy Static Site

on:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build all outputs
        run: bin/cruella build all

      - name: Deploy via rsync
        env:
          DEPLOY_DEST: ${{ secrets.DEPLOY_DEST }}
        run: bin/cruella deploy