name: Build Static Site

on:
  workflow_dispatch:  

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build HTML
        run: bin/cruella build html

      - name: Build PDFs
        run: bin/cruella build pdf

      - name: Build Slides
        run: bin/cruella build slides

      - name: Archive site outputs
        uses: actions/upload-artifact@v4
        with:
          name: site-outputs
          path: |
            public/
            pdfs/
            slides/